### ISSUE TITLE
Full Stack projektin katselmointi

### ISSUE THREAD

**Issue by Kaltsoon** [saarikt1/local-lunch#6]
# Katselmointi

Terve @saarikt1! Tässä lyhyt katselmointi Full Stack kurssin projektistasi.

### Mitä tein?

Selasin tarjontaa kartalla.

### Kokemus

- Sovelluksella on käyttötarkoitukseen sopiva käyttöliittymä, hienoa! 🏆
- Geneerisen "React App"-faviconin voisi muuttaa kuvaavammaksi
- Kartalla voisi näkyä lounaspaikat sijainnista riippumatta (esimerkiksi aktiivisen karttaikkunan perusteella)
- Olisi kätevää, jos sijainnin voisi asettaa myös käsin

## Koodi

- Frontend-puolen koodi on selkeästi organisoitua, hyvä!
- Reduxin actioneita kannattaa luoda nk. [action creator](https://redux.js.org/basics/actions#action-creators)-funktioiden avulla sen sijaan, että käyttäisi [suoraan objekteja](https://github.com/saarikt1/local-lunch/blob/master/client/src/redux/restaurant.ts#L157) `dispatch`-kutsun yhteydessä. Kun actionin luonti on abstraktoitu funktion avulla, sitä on helpompi muuttaa tulevaisuudessa ilman suurempaa refaktorointia
- Syvien tietorakenteiden immutable päivittäminen Reduxin reducereissa puhtaalla JavaScriptilla on melko työlästä. [Immer](https://www.npmjs.com/package/immer)-kirjasto helpottaa tätä huomattavasti
- [Redux Toolkit](https://redux-toolkit.js.org/) tarjoaa todella hyviä työkaluja Reduxin käyttöön. Esim. [createReducer](https://redux-toolkit.js.org/usage/usage-with-typescript#createreducer)-funktio vähentää reducerien boilerplate koodia huomattavasti
- Mainio idea käyttää Formik-kirjastoa lomakkeiden tilanhallinnassa
- Hyvän näköistä e2e- ja yksikkötestausta
- Kätevää abstraktoida `navigator.geolocation.getCurrentPosition` promisen palauttavaksi [funktioksi](https://github.com/saarikt1/local-lunch/blob/master/client/src/redux/location.ts#L63). Callback-rajapinta on vähän hankala
- Asynkronisiin operaatioihin (kuten API-kutsut,) liittyvät operaatiot tuottavat Reduxin kanssa usein jonkin verran toisteellista boilerplate-koodia. [React Query](https://react-query.tanstack.com/) kirjaston avulla asynkronisten operaatioiden tilanhallinnan voi helposti abstraktoida yksinkertaisiksi hookeiksi
- Myös backend-puolen koodi on selkeästi organisoitua, hienoa!
- [SQL-koodia](https://github.com/saarikt1/local-lunch/blob/master/src/services/restaurantService.ts#L13) ei kannata sisällyttää sovelluslogiikkaan. Tee mielummin tietokantaoperaatioihin joku abstraktio, kuten `RestaurantRepository` (nimi tulee [Repository](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-design)-suunnittelumallista), jossa on fuktioita, tai metodeja, kuten `create`, `findById`, `find`, jne. Jos SQL-koodia ei halua kirjoittaa itse, kannattaa tutustua [TypeORM](https://typeorm.io/#/)-kirjastoon 

## Kokonaisuus

Sovelluksella on selkeä ja hyödyllinen käyttötarkoitus, ja sen toteutus on kunnossa. Koodi on kaikilta osin hyvin organisoitua ja pääosin erittäin laadukasta. Kirjastoja ja teknologioita, kuten TypeScript ja Material-UI on käytetty järkevästi. Backendin-puolella sovelluslogiikan eristämistä tietokantaoperaatioista voisi vielä parantaa.

**Comment by saarikt1** [comment]
Moi @Kaltsoon! 

Kiitos paljon katselmoinnista. En odottanutkaan, että olisin saanut näin laadukasta palautetta kurssityöstä 👍 Tätä projektia on vielä tarkoitus jatkaa, minkä vuoksi arvostan erityisesti ehdotuksia sopivista kirjastoista tai arkkitehtuurisista muutoksista.

Kiitos!
